### ISSUE TITLE
npm install fails on Xenial

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/Yukon#4]
Hey @Zarkopafilis, I suspect that my node is probably too old (I really should replace my worn out Mint 18 with Kubuntu Bionic) (also, it's my first time doing anything with Node at all). At first, `npm install` failed when installing `chromedriver` with a complaint that the executable `node` is unavailable, which I fixed by installing the APT package `nodejs-legacy` ("legacy" in the name seems like a red flag). Then this happened:

```
pavel@pavel-workstation $ npm install chromedriver

> chromedriver@2.46.0 install frontend/node_modules/chromedriver
> node install.js

frontend/node_modules/chromedriver/lib/chromedriver.js:5
  let port = 9515;
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (frontend/node_modules/chromedriver/install.js:5:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.7
npm WARN optional Skipping failed optional dependency /sane/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.7
npm WARN @vue/server-test-utils@1.0.0-beta.29 requires a peer of vue-server-renderer@2.x but none was installed.
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none was installed.
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "chromedriver"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.46.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chromedriver@2.46.0 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     frontend/npm-debug.log
```

I can PM my `npm-debug.log` if neccessary.

<sub>(I know that there are a pull requests and forum threads waiting for my attention, I will get to those first thing tomorrow; the last few days were spent between stupid meetings and finishing up the PyDSDL parser)</sub>

**Comment by Zarkopafilis** [comment]
The particular chromedriver dependency is only used for the e2e tests.
It works on my mac. Just to be sure, can you generate a new empty hello project with
the [vue cli](https://cli.vuejs.org/guide/creating-a-project.html#vue-create)? Include unit tests with jest and e2e tests with nightwatch. If this fails too, I'll set up a VM and work this out.

**Comment by pavel-kirienko** [comment]
Okay, I see what the problem is now:

```
You are using Node v4.2.6, but this version of vue-cli requires Node >=8.9.
Please upgrade your Node version.
```

I got rid of the node which I installed through APT and installed an official snap package v11.x, everything seems to be working well now. I think we should specify in the README that the minimum required node version is v11.
